#!/bin/sh

case $BLOCK_BUTTON in
	1) bluetoothctl power on > /dev/null; bluetoothctl connect FF:FF:FF:FF:FF:FF > /dev/null ;;
	2) bluetoothctl power off > /dev/null  ;;
	3) bluetoothctl power on > /dev/null ;;
esac

powered=$(bluetoothctl show | awk '/Powered: /{print}' | cut -f2 | cut -d " " -f2)
connected=$(bluetoothctl info | cut  -d" " -f1)

if [ "$powered" == "yes" ]; then
  msg=✅;
else
  msg=⛔;
fi;

if [ "$connected" == "Missing" ]; then
  echo $msg 🔇;
else
  echo $msg 🔊;
fi;
